
import "./globals.css";
import Navbar from "@/Compoents/Navbar";


export const metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
